default: &default 
  adapter: postgresql 
  encoding: unicode 
  pool: 5

development:
  <<: *default
  database: angipl_2021_development

test:
  <<: *default
  database: angipl_2021_test

production:
  <<: *default
  database: angipl_2021_production
  username:
  password: